version: 2

jobs:
  build:
    working_directory: ~/python-ci

    docker:
      - image: circleci/python:3.8.8-buster

    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
              sudo pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
              ./manage.py test
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

      - run:
          name: Run pylint
          command: |
              pylint --output-format=colorized --load-plugins pylint_django --django-settings-module=baggysoapshop.settings baggysoapshop/ custom_apps/
