ZONES = {"United Kingdom": ["United Kingdom", "Guernsey", "Isle of Man", "Jersey"],
         "Europe": ["Albania", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium",
                    "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark",
                    "Estonia", "Faroe Islands", "Finland", "France", "Georgia", "Germany", "Gibraltar",
                    "Greece", "Greenland", "Holy See (Vatican City State)", "Hungary", "Iceland",
                    "Ireland", "Italy", "Kazakhstan", "Kyrgyzstan", "Latvia", "Liechtenstein",
                    "Lithuania", "Luxembourg", "Macedonia", "Republic of", "Malta", "Moldova, Republic of",
                    "Monaco", "Montenegro", "Netherlands", "Norway", "Poland", "Portugal", "Romania",
                    "Russian Federation", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain",
                    "Sweden", "Switzerland", "Tajikistan", "Turkey", "Turkmenistan", "Ukraine", "Uzbekistan"],
         "World Zone 1": ["Afghanistan", "Algeria", "Angola", "Anguilla",
                          "Antarctica", "Antigua and Barbuda", "Argentina", "Aruba", "Bahamas",
                          "Bahrain", "Bangladesh", "Barbados", "Belize", "Benin", "Bermuda", "Bhutan",
                          "Bolivia, Plurinational State of", "Bonaire, Sint Eustatius and Saba",
                          "Botswana", "Bouvet Island", "Brazil",
                          "Brunei Darussalam", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
                          "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad",
                          "Chile", "China", "Colombia", "Comoros", "Congo",
                          "Congo, The Democratic Republic of the", "Costa Rica", "Côte d'Ivoire",
                          "Cuba", "Curaçao", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
                          "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Ethiopia",
                          "Falkland Islands (Malvinas)", "French Guiana", "Gabon", "Gambia",
                          "Ghana", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea",
                          "Guinea-Bissau", "Guyana", "Haiti", "Heard Island and McDonald Islands",
                          "Honduras", "Hong Kong", "India", "Indonesia", "Iran, Islamic Republic of",
                          "Iraq", "Israel", "Jamaica", "Japan", "Jordan", "Kenya",
                          "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait",
                          "Lebanon", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Malaysia",
                          "Maldives", "Mali", "Marshall Islands", "Martinique", "Mauritania", "Mauritius",
                          "Mayotte", "Mexico", "Micronesia, Federated States of", "Mongolia",
                          "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal",
                          "Nicaragua", "Niger", "Nigeria", "Northern Mariana Islands", "Oman",
                          "Pakistan", "Palau", "Palestine, State of", "Panama", "Paraguay", "Peru",
                          "Philippines", "Puerto Rico", "Qatar", "Réunion",
                          "Rwanda", "Saint Barthélemy", "Saint Helena, Ascension and Tristan da Cunha",
                          "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin (French part)",
                          "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines",
                          "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles",
                          "Sierra Leone", "Sint Maarten (Dutch part)", "Somalia", "South Africa",
                          "South Georgia and the South Sandwich Islands", "South Sudan", "Sri Lanka",
                          "Sudan", "Suriname", "Swaziland", "Syrian Arab Republic",
                          "Taiwan, Province of China", "Tanzania, United Republic of", "Thailand",
                          "Timor-Leste", "Togo", "Trinidad and Tobago", "Tunisia", "Turks and Caicos Islands",
                          "Uganda", "United Arab Emirates", "Uruguay", "Vanuatu",
                          "Venezuela, Bolivarian Republic of", "Viet Nam", "Virgin Islands, British",
                          "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
         "World Zone 2": ["American Samoa", "Australia", "British Indian Ocean Territory",
                          "Christmas Island", "Cocos (Keeling) Islands", "Cook Islands", "Fiji",
                          "French Polynesia", "French Southern Territories", "Kiribati",
                          "Lao People's Democratic Republic", "Macao", "Nauru", "New Caledonia",
                          "New Zealand", "Niue", "Norfolk Island", "Papua New Guinea", "Pitcairn",
                          "Singapore", "Solomon Islands", "Tokelau", "Tonga", "Tuvalu"],
         "World Zone 3": ["United States", "United States Minor Outlying Islands"]}
